server:
  port: 8082
spring:
  application:
    name: article
  profiles:
    active: dev
  rabbitmq:
    host: 10.8.0.78
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisherConfirms: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.news.client.article.entity
