spring:
  ymlversion: 1.1
  datasource:
    druid:
      url: jdbc:mysql://10.8.0.10:3306/cloud_news?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      max-active: 5
      min-idle: 1
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        #管理界面用户吗
        login-username: admin
        #管理界面密码
        login-password: admin
